EVENT_ID_COLUMN = "EVENT_ID"
EVENT_NAME_COLUMN = "ACTIVITY"
EVENT_TIME_COLUMN = "TIMESTAMP"

OBJECT_TYPE_COLUMN = "OBJECT_TYPE"
OBJECT_ID_COLUMN = "OBJECT_ID"
OBJECT_TYPE_TWO_COLUMN = "OBJECT_TYPE_2"
OBJECT_ID_TWO_COLUMN = "OBJECT_ID_2"
NODE_ID_SEPARATOR = "_"
